### ISSUE TITLE
Updating to php-cgi instead of using cli causing whole lot of issues

### ISSUE THREAD

**Issue by sameerpanjwani** [CpanelInc/php-cli#1] opened 2016-08-24 13:25 UTC
I'm unable to use composer properly because it doesn't run on php-cgi

`Warning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI`

Then I use the laravel framework which has commands like "php artisan" those don't work either.

Ref: https://github.com/CpanelInc/php-cli/commit/3645e9d50f4ab9705a49494c40e6f650b43bad45

**Comment by JPerkster** [comment] 2016-08-24 13:27
Hi,

How are you running Composer? Could you provide replication steps on that? \

If you need php-cli, you can call the binary directly with '/opt/cpanel/ea-php##/root/usr/bin/php'.

**Comment by sameerpanjwani** [comment] 2016-08-24 13:31
There nothing special I'm doing about running those commands.

I just run `composer install` or `php artisan`.  They work independently if i call `opt/cpanel...` but that doesn't help because because the composer post-install commands call some other commands like `php artisan` which then dont work on cgi. 

Otherwise I'll have to remove all my composer post-install and post-update commands and run them another way. But that doesn't sound like an ideal solution.

**Comment by JPerkster** [comment] 2016-08-24 13:35
How did this work on EA3? This change was a temp workaround to the problem in that in EA3, '/usr/bin/php' points to php-cgi. In any OS distribution of PHP (CentOS, Debian, etc), '/usr/bin/php' points to php-cli. 

In EA3, '/usr/bin/php' pointed to '/usr/bin/php-cgi'. 
In EA4, '/usr/bin/php' pointed to '/usr/bin/php-cli'. We've *just* changed that to go back to the EA3 behaviors due to crontabs amongst other things not working properly with php-cli. 

I'd recommend updating your scripts to point to the binary directly. 

Would it help if we provided a '/usr/bin/php-cli' wrapper/binary that you could call directly outside of calling the SCL binary? It'll save a few keystrokes, but that's about it.

**Comment by sameerpanjwani** [comment] 2016-08-24 13:43
Not sure how it worked on EA3 or how it worked on EA4 till before the update. Unless I'm guessing it's the wrong commit and some other commit related to the EA4 latest update is causing this issue. 

I can point to the binary but that means I can't use the composer post-install commands and I can't update the composer post-install commands to point to the binary because then it would not work on our local systems. So to make it work would mean we'd have to run a series of commands locally differently and on the server differently because we can't rely on composer post-install commands anymore. That's quite inconvenient.

But I can't understand then how did it work previously. Everything has been so smooth for months together. The only difference has been that we've updated to php 7 from the time we updated to EA4. So would php 7.0 and EA4 and this cgi combination cause issues? That's my only guess as to what could be different because it did work perfectly up til this last update and worked perfectly as well a couple of months back when we were on EA3 and php 5.6

**Comment by JPerkster** [comment] 2016-08-24 14:07
Hi,

It's definitely this commit causing you issues, but my primary concern is how it worked in EA3, since all we've done is replicated that environment in EA4. I don't think the PHP 7 upgrade would do it. It's possible you were using '/usr/bin/php-cli' instead of '/usr/bin/php' in EA3. 

I do think you'll need to update some commands to get it working fully, but while that's not really the best, I think it'll get you close for now.

**Comment by Cacasapo** [comment] 2016-08-24 15:33
Same issue + **https://forums.cpanel.net/threads/easyapache-4-cron-issue.532861/page-2#post-2288031**

Basically, php cli arguments aren't being parsed and php cli now requires absolute paths. Borks all sorts of things.

**Comment by JPerkster** [comment] 2016-08-24 16:13
Hi @Cacasapo,

Could you verify your include_path for PHP? That would stop loading of '.'. Your include path should look something like:
include_path => .:/opt/cpanel/ea-php56/root/usr/share/pear => .:/opt/cpanel/ea-php56/root/usr/share/pear

**Comment by Cacasapo** [comment] 2016-08-24 16:16
@JPerkster It's set to the default: 
include_path => .;/path/to/php/pear => .;/path/to/php/pear

**Comment by JPerkster** [comment] 2016-08-24 16:19
Hi,

That include path is bad wrong. The default include_path should look like:

[root@11 ~]# /opt/cpanel/ea-php55/root/usr/bin/php -i | grep -i include_path
include_path => .:/opt/cpanel/ea-php55/root/usr/share/pear => .:/opt/cpanel/ea-php55/root/usr/share/pear

If you adjust your include path in your local.ini, can you see if this works?

**Comment by Cacasapo** [comment] 2016-08-24 16:27
Even though the path is incorrect, it still includes . as the first argument and was working prior to the shift to php-cgi. 
In fact, removing /usr/local/bin/php and linking it to /opt/cpanel/ea-php56/root/usr/bin/php gets things working again, including composer and relative path execution. 
Of course, this borks CLI PHP7 execution, but works for testing.

`[root@rwh ~]# ls -l /usr/local/bin/php
lrwxrwxrwx 1 root root 37 Aug 24 10:47 /usr/local/bin/php -> /opt/cpanel/ea-php56/root/usr/bin/php
[root@rwh ~]# php args.php 1 2 3 4
int(5)
array(5) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
}
[root@rwh ~]# php -i | grep include_path
include_path => .;/path/to/php/pear => .;/path/to/php/pear
[root@rwh ~]#
`

**Comment by Cacasapo** [comment] 2016-08-24 16:37
Here's the relative path and argument issue while executing php-cgi directly. The issue seems to be with that binary, but this is just my uneducated guess.

[root@rwh ~]# php -i | grep include_path
include_path => .;/opt/cpanel/ea-php56/root/usr/share/pear => .;/opt/cpanel/ea-php56/root/usr/share/pear
[root@rwh ~]# /opt/cpanel/ea-php56/root/usr/bin/php-cgi args.php
Status: 404 Not Found
Content-type: text/html; charset=UTF-8

No input file specified.
[root@rwh ~]# /opt/cpanel/ea-php56/root/usr/bin/php-cgi ./args.php 1 2 3 4
Content-type: text/html; charset=UTF-8

NULL
NULL
[root@rwh ~]# /opt/cpanel/ea-php56/root/usr/bin/php args.php 1 2 3 4
int(5)
array(5) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
}
[root@rwh ~]#

**Comment by JPerkster** [comment] 2016-08-24 16:37
Hi,

We have a case open for the include_path: EA-4753. We're fixing that now. 

My include_path is properly setup on my EA4 install, and I'm having no issues running your test script. It appears the include_path is not proper, thus PHP isn't reading / using it, and so that's not working. Could you fix your include_path and confirm for me?

```
• [root@jperkins:~]# /usr/bin/php test.php 1 2 3 4 5
X-Powered-By: PHP/5.5.30
Content-type: text/html

int(6)
array(6) {
  [0]=>
  string(8) "test.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
  [5]=>
  string(1) "5"
}
```

**Comment by Cacasapo** [comment] 2016-08-24 16:38
@JPerkster Posted it at the same time. See above!

**Comment by Cacasapo** [comment] 2016-08-24 16:39
Can you run your test with 5.6?

**Comment by JPerkster** [comment] 2016-08-24 16:44
Hi,

So it looks like that php-cgi doesn't like those arguments passed on the command line. php-cli does tho:

```
root@cpanel [~]# /opt/cpanel/ea-php56/root/usr/bin/php -i | grep -i include_path
include_path => .:/opt/cpanel/ea-php56/root/usr/share/pear => .:/opt/cpanel/ea-php56/root/usr/share/pear
root@cpanel [~]# /opt/cpanel/ea-php56/root/usr/bin/php test.php 1 2 3 4 5
int(6)
array(6) {
  [0]=>
  string(8) "test.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
  [5]=>
  string(1) "5"
}
root@cpanel [~]# /opt/cpanel/ea-php56/root/usr/bin/php-cgi test.php 1 2 3 4 5
Content-type: text/html; charset=UTF-8

NULL
NULL
```

This is exasperated by us changing /usr/bin/php to point to php-cgi. 

It sounds like we need a '/usr/local/bin/php' that points to php-cli, so that we match EA3 behavior more closely. Since '/usr/local/bin' is set first in $PATH, this will be called first, and thus provide php-cli. If /usr/bin/php is called, that'll be php-cgi. 

Does that sound like a proper way forward that'll fix the issues you're seeing?

**Comment by Cacasapo** [comment] 2016-08-24 16:50
Having php-cli and php-cgi available but in different paths in PATH would be an extra complication for you guys, but I reckon it would allow someone needing php-cgi to somewhat easily get to it.

That said, it looks like pointing /usr/local/bin/php to php-cli would solve both the relative path and argument issues.

**Comment by JPerkster** [comment] 2016-08-24 17:13
It's not too hard to have our RPM spit out another binary in a new place. We've opened case EA-5106 to get this done, and I hope that we can have it complete, tested and pushed out next Tuesday. 

Thank you @Cacasapo and @sameerpanjwani for your report and help!

**Comment by Cacasapo** [comment] 2016-08-24 17:15
Thanks for the quick response to the issue!

**Comment by skurtn** [comment] 2016-08-24 17:17
Adding /usr/local/bin/php certainly adds more cruft to the RPMs, but, such is the life for maintaining backwards compatibility and to ensure an easier migration.

I personally would love to have a path forward to help systems migrate to the new shiny way of doing things (which would be in-line with current OS standards).  Maybe this transition can happen at a future date.

**Comment by Cacasapo** [comment] 2016-08-24 17:38
/usr/local/bin/php would just be reverting to php-cli while /usr/bin/php would remain php-cgi. Yeah, it seems needlessly complicated.

Is there some reason to want to run php-cgi in the CLI? Just seems to break things.

**Comment by skurtn** [comment] 2016-08-24 17:59
We have several customers with administrative scripts, administrative crontabs, and user crontabs that explicitly use this path, assuming it's the cgi variant.

With respect to the distinction, the cgi variant automatically changes into the home directory of the user executing the script.  The lack of directory changing breaks many of these scripts.

**Comment by Cacasapo** [comment] 2016-08-24 18:26
The CGI variant, at least in this case, seems to ignore arguments, which does complicate things for people with crons that have arguments. 
Sound complicated, advancing and keeping things from breaking!

I forked ea-php-cli and reverted the commit that made the cli->cgi change. Will use that until an official fix is out.

**Comment by zackcote** [comment] 2016-08-24 20:00
Looking forward to a fix, glad to have found this thread!

**Comment by prhost** [comment] 2016-08-24 20:22
I am using the path `/opt/cpanel/ea-php70/root/usr/bin/php` to cpanel out a fix.

**Comment by rafaflm** [comment] 2016-08-24 20:26
https://forums.cpanel.net/threads/easyapache-4-update-august-23-2016.565651/

It was a PITA to take my server back

PITA  Pain In The Ass

**Comment by sameerpanjwani** [comment] 2016-08-25 02:02
For those using `composer install` and have various post-install commands, till a fix is issued, I've got things working by calling `scl enable ea-php70 'composer install'` (my host provided me with this, not sure what `scl` means but it works better than calling `opt/cpanel/ea-php70/...` because for some reason that doesn't invoke the `post-install` commands of composer using cli again).

For now I'm calling all my commands on the server like this, another example `scl enable ea-php70 'php artisan:migrate'`

You need to replace `php70` with `php{version}` if you intend to use this. 

So this method temporarily solves my problem till the fix is issued.

**Comment by skurtn** [comment] 2016-08-25 02:36
@sameerpanjwani, that is the best/preferred way to execute any application that uses the Redhat Software Collections (SCL) system.

**Comment by zackcote** [comment] 2016-08-25 11:31
For anyone like @sameerpanjwani who doesn't want to rewrite their own commands or has commands auto-generated as part of a deployment process, you can add a quick function to your .bashrc until this is resolved:

```
function php() { /opt/cpanel/ea-php70/root/usr/bin/php "$@" ;}
```

Just replace the `ea-php70` with your php version.

**Comment by dotsam** [comment] 2016-08-25 22:11
You can also modify/create the file `/usr/bin/php_cli.yaml` and add the line 
```
php_bin_pattern: /opt/cpanel/ea-php%s/root/usr/bin/php
```
to get the old behaviour back.

**Comment by JPerkster** [comment] 2016-08-25 22:32
Hi,

We're going to be reverting this commit this afternoon, until we can bring in /usr/local/bin/php pointing to php-cli. Sorry for the problems everyone, and thanks for the super quick report!

**Comment by JPerkster** [comment] 2016-08-26 00:12
Hi,

We've pushed the updated packages to the mirrors. It looks big, but a bunch of PHP packages rebuilt after we updated php-cli. Could you test it out and let us know if things are back working properly?

**Comment by Cacasapo** [comment] 2016-08-26 00:21
ea-php-cli.x86_64 0:0.0.6-5.5.1.cpanel + a bunch of other stuff updated.
CLI PHP is back to normal on test box.

[root@tempwhm ~]# php args.php 1 2 3 4
int(5)
array(5) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
}

**Comment by zackcote** [comment] 2016-08-26 01:11
We're back! Looks good @JPerkster

**Comment by JPerkster** [comment] 2016-08-26 13:44
Rock on, thanks for the confirmation. I'm closing this out, and I'll probably re-open once we get '/usr/local/bin/php' setup, as I'd love for you guys to test that we hit the mark with that update.

**Comment by JPerkster** [comment] 2016-09-14 14:35
Good morning,

We've made an update to the php-cli package, and added '/usr/local/bin/php' that points to php-cli. Could someone that was affected by this earlier test this out for me and see if we hit our mark?

You can adjust your EA4.repo file with the following:

```
[EA4]
name=EA4 ( EasyApache 4 )
baseurl=http://ea4testing.cpanel.net/CentOS/6/EA4/x86_64/
#mirrorlist=http://httpupdate.cpanel.net/ea4-c$releasever-$basearch-mirrorlist
gpgcheck=1
gpgkey=https://securedownloads.cpanel.net/cPanelPublicRPMKey.asc
enabled=1
cost=1
```

Once done:
`yum clean all ; yum update`

You should get the updates.

I'd love feedback to see how it works with your systems.

**Comment by Cacasapo** [comment] 2016-09-14 14:54
Looks ok with that args script we were using. I don't have any crons running on the test server, but I'm willing to run any other tests you may feel necessary.

Unrelated: Got lots of bitching from ea-php*-php-intl, ea-php56-php-fpm and some others about missing libs, so I just installed ea-php-cli by itself. I reckon that's due to the testing repo.

```
[root@tempwhm ~]# php args.php 1 2 3 4 5
int(6)
array(6) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
  [5]=>
  string(1) "5"
}
[root@tempwhm ~]# php -v
PHP 5.6.25 (cli) (built: Aug 25 2016 17:00:38)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by JPerkster** [comment] 2016-09-14 14:57
Hi,

@Cacasapo  Thanks for the update! 

One note for others, if the argv / argc isn't working, please ensure that 'register_argc_argv=1' in your php.ini.

**Comment by JPerkster** [comment] 2016-09-14 14:57
@sameerpanjwani  Would you be able to test out the update with Composer for me?

**Comment by Cacasapo** [comment] 2016-09-14 15:00
Composer OK here.
```
[root@tempwhm ~]# composer self-update
Updating to version 1.2.1 (stable channel).
    Downloading: 100%
Use composer self-update --rollback to return to version 1.1.1
[root@tempwhm ~]# composer diagnose
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
[root@tempwhm ~]#
```

**Comment by JPerkster** [comment] 2016-09-20 19:32
I'm sending updated EA4 RPMs to the mirrors right now. This includes the updates for php-cli, which provides a new '/usr/local/bin/php' which points to the php-cli binary. '/usr/bin/php' points to the php-cgi binary. Please let us know if you see any problems. Thanks!

**Comment by Cacasapo** [comment] 2016-09-21 11:17
In CLI I'm getting the correct php `ea-php-cli Copyright 2016 cPanel, Inc.`, but the update blew up cron, which for some reason is using `PHP 5.6.26 (cgi-fcgi) (built: Sep 19 2016 15:07:57)` and thus is not accepting arguments.

Too many kinks in the pipe. Prepare for the flood!

**Comment by JPerkster** [comment] 2016-09-21 13:21
@Cacasapo Can you let me know what exactly is going on? php-cgi accepts arguments just fine (provided register_argc_argv=On in php.ini / local.ini):

```
root@cpanel [~]# /usr/bin/php ./args.php 1 2 3 4
Content-type: text/html

int(5)
array(5) {
  [0]=>
  string(10) "./args.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
}
```

**Comment by Cacasapo** [comment] 2016-09-21 13:33
register_argc_argv is off by default in php56 and php7, at least on my install, with the following note:
"For performance reasons, this feature should be disabled; on production servers."

The issue is only cropping up in cron, because cron's PATH variable (on my install. I'm traveling and don't have access to my test server at the moment), obtained by running` echo $PATH > /home/user/phpv.txt` as a user cronjob, is  /usr/bin:/bin, which runs cgi-fcgi.

**Comment by JPerkster** [comment] 2016-09-21 13:38
Hi,

If the cron is calling 'php' only, then yes, it'll call the php-cgi binary, which is the same in EA3:

```
• [root@jperkins64:~]# /usr/bin/php -v
PHP 5.6.26 (cgi-fcgi) (built: Sep 20 2016 14:27:22)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

If you want php-cgi to accept arguments, then register_argc_argv must be on. This hasn't changed from EA3. I'm still not fully understanding what isn't working right now. Could you be super specific about the issue, and how to replicate it?

**Comment by Cacasapo** [comment] 2016-09-21 14:31
Yeah, various user crons are callling php without a path. This is a native EA4 install and I don't remember how my EA3 crons ran, but I can see confusion ensuing when users set up crons and have to specify a full php path. 
Methinks the default should be php-cli all around, with an option to specify php-cgi in cron if needed. 
Of course, I don't know what that'd break. 

For me, the monkey wrench appears to be that the cron PATH differs from the user PATH variable. 
For example, the WHMCS docs for cron seem to assume php-cli, since they show the cron setup without a full path. Running it php-fcgi would break that, without register_argc_argv, which is off by default.

If it stays this way it's no big deal for me, because I'd just modify and compile my own ea-php-cli to avoid this issue, since register_argc_argv would, apparently, be a performance hit . 
Don't know how many others will chime in regarding this, but I presume there will be fireworks.

**Comment by JPerkster** [comment] 2016-09-21 14:37
Hi,

In EA3, the CRON path is the same ( '/usr/bin:/bin' ). This means that in EA3, if users are simply calling 'php', they are going to get php-cgi. This is the exact same in EA4, with our latest changes.

EA3 had 'register_argc_argv' on by default. If you didn't notice a performance hit on EA3, then you won't see it on EA4.

I don't think we'll be seeing many 'fireworks' here, as we've simply matched EA3 behaviors. You simply need to enable 'register_argc_argv'. 

If you see any other problems, please do let me know!

**Comment by Cacasapo** [comment] 2016-09-21 14:43
If register_argc_argv won't cause noticeable performance issues, then that's the way to go.
Perhaps enabling it by default would also be the way to go on EA4?

I've enabled it in PHP56/PHP7 and cron is still bitching, so I'm going to band-aid this and deal with it when I get back home, this weekend.

**Comment by JPerkster** [comment] 2016-09-21 15:00
Hi,

You still haven't advised what exactly the cron is doing. Can you provide output / replication steps / errors so that I can investigate?

Thanks!

**Comment by Cacasapo** [comment] 2016-09-21 18:05
I'll do some proper troubleshooting once I get back home. Right now I just overwrote the cgi executable with the cli one. Quick and dirty.

**Comment by MarioKnight** [comment] 2016-09-22 15:43
In case this helps (hopefully it won't add to the complications), I was told that crons that use WP-CLI stopped working following my upgrade to EasyApache 4 last night.

`30 0,6,12,18 * * * /usr/local/bin/wp --path="/home/xxxxx/public_html" cron event run nameofevent > /home/xxxx/logs/filename-datetimestamphere`

As others noted with their php-calling crons, when I tested the same commands running in command line, they ran with no issues.  I eventually found a relevant thread in the cPanel forums which lead me to this issue.  Adjusting `register_argc_argv` to On managed to fix this for me.  It appears that WP-CLI saw the new PHP which was good, and seems to more or less confirm `register_argc_argv` is the deciding factor with cron jobs for anything that calls upon PHP:
```
# wp --info
PHP binary:	/opt/cpanel/ea-php56/root/usr/bin/php
PHP version:	5.6.26
php.ini used:	/opt/cpanel/ea-php56/root/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1
```
Hopefully this can help some, at the very least, I hope that others who have the same issue as me can find this discussion and fix easier.  Thanks to everyone in this thread for discovering the fix.

**Comment by Cacasapo** [comment] 2016-09-26 16:11
@JPerkster 
I'm getting mixed results with the new setup. Magento seems happy, but Hubzilla doesn't like it, even with register_argc_argv on, so I'm still inclined towards using a hammer on it.

```
Cron:
* * * * *  cd /home/user ; php -i | grep argv > /home/user/phpv.txt
Result (OK):
<tr><td class="e">register_argc_argv</td><td class="v">On</td><td class="v">On</td></tr>
<tr><td class="e">_SERVER["argv"]</td><td class="v"><pre>Array


Cron:
* * * * *  cd /home/user ; php args.php 1 2 3 4 5 >  /home/user/args.txt
Result (OK):
int(6)
array(6) {
  [0]=>
  string(8) "args.php"
  [1]=>
  string(1) "1"
  [2]=>
  string(1) "2"
  [3]=>
  string(1) "3"
  [4]=>
  string(1) "4"
  [5]=>
  string(1) "5"
}

Hubzilla test install Cron:
* * * * *       cd /home/user/user.domain.com; php Zotlabs/Daemon/Master.php Cron
Mail received(not ok):
Status: 404 Not Found
Content-type: text/html; charset=UTF-8

No input file specified.
```

**Comment by JPerkster** [comment] 2016-09-26 16:14
What is the include_path for PHP where you're getting 'No input file specified'? That needs to include '.' in it.

**Comment by Cacasapo** [comment] 2016-09-26 16:19
The odd thing is that it does not error out if I replace pgp-cgi with php-cli.

From inside cron:
include_path => .;/opt/cpanel/ea-php56/root/usr/share/pear

**Comment by JPerkster** [comment] 2016-09-29 05:16
@Cacasapo,

If you specifically need php-cli, you can point the cron to '/usr/local/bin/php'. I'd like to reach out and see if I can ensure your issues are getting fixed in the correct ways. Would you mind throwing in a support ticket with 'Attn Jacob' in the subject, and it would be even more awesome if you could give us access to a system to see what you are seeing.

As a note, we've made a change in our default php.ini files that sets register_argc_argv = On by default. This should allow crontabs and other scripts like we've seen above work without any other problems. You'll see these changes in our PHP repositories here on github. We hope to push these out public soon. While this won't fix existing EA4 installations, it will on new installs. You should also be able to issue a 'yum reinstall php55*', as an example, to get the updated php.ini (if you have not made any changes to it).

I'd like to leave this issue open a bit longer, as I'd like to verify we've got you running well.

**Comment by Cacasapo** [comment] 2016-09-29 09:07
I just want users to be able to read and follow install docs for whatever they're trying to run and to get said apps running without additional steps, or worse: me holding their hands. 
Besides, I really hate pgp-cgi's output when redirected to a text file, with all that HTML fouling things up.

I've created ticket 7731529 with root access so you can take a gander.

**Comment by dotsam** [comment] 2017-07-13 19:46
With the changes in the new version, if you want to keep all command line binaries running the plan cli version of `php` then your `/usr/bin/php_cli.yaml` file needs to read as follows:
```
php_bin_pattern: /%s/%s/root/usr/bin/php
```

**Closed** 2017-09-08 14:46 UTC
